{
 "title": "Mead Tracker",
 "time": { "from": "2024-07-09T03:14:02.000Z", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "session",
    "label": "Session",
    "query": "SELECT sessionName FROM rapt_pill_metrics"
   },
   {
    "name": "min_time",
    "query": "SELECT MIN(\"timestamp\") FROM \"rapt_pill_metrics\" WHERE \"sessionName\" =~ /^$session$/\n"
   },
   {
    "name": "max_time",
    "query": "SELECT MAX(\"timestamp\") FROM \"rapt_pill_metrics\" WHERE \"sessionName\" =~ /^$session$/\n"
   }
  ]
 },
 "panels": [
  { "title": "HUD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "session" },
  {
   "title": "Current Gravity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"curr_gravity\" AS \"current gravity\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nAND \"timestamp\" <= $max_time "
    }
   ]
  },
  {
   "title": "ABV%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"abv\" AS \"abv\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nAND \"timestamp\" <= $max_time "
    }
   ]
  },
  {
   "title": "Temp",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"temperature\" AS \"temp\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nAND \"timestamp\" <= $max_time "
    }
   ]
  },
  {
   "title": "Grav Vel",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"gravity_velocity\" AS \"velocity\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nAND \"timestamp\" <= $max_time "
    }
   ]
  },
  {
   "title": "Battery%",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"battery\" AS \"battery\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nAND \"timestamp\" <= $max_time "
    }
   ]
  },
  {
   "title": "Starting Gravity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "SG" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT \"curr_gravity\" AS \"current gravity\"\nFROM \"rapt_pill_metrics\"\nWHERE \"sessionName\" =~ /^$session$/\nAND \"timestamp\" >= $min_time\nLIMIT 1"
    }
   ]
  },
  { "gridPos": { "h": 8, "w": 19, "x": 0, "y": 5 } }
 ]
}